// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class MultiLevel
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject multiLevelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.MultiLevel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ItemID("ItemID"),
		Name("Name"),
		ParentLevel("TreeViewDemo.ParentLevel");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MultiLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.MultiLevel"));
	}

	protected MultiLevel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject multiLevelMendixObject)
	{
		if (multiLevelMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.MultiLevel", multiLevelMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.MultiLevel");

		this.multiLevelMendixObject = multiLevelMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MultiLevel.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.MultiLevel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.MultiLevel.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.MultiLevel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeviewdemo.proxies.MultiLevel(context, mendixObject);
	}

	public static treeviewdemo.proxies.MultiLevel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.MultiLevel.initialize(context, mendixObject);
	}

	public static java.util.List<treeviewdemo.proxies.MultiLevel> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<treeviewdemo.proxies.MultiLevel> result = new java.util.ArrayList<treeviewdemo.proxies.MultiLevel>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TreeViewDemo.MultiLevel" + xpathConstraint))
			result.add(treeviewdemo.proxies.MultiLevel.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ItemID
	 */
	public final java.lang.Long getItemID()
	{
		return getItemID(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemID
	 */
	public final java.lang.Long getItemID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ItemID.toString());
	}

	/**
	 * Set value of ItemID
	 * @param itemid
	 */
	public final void setItemID(java.lang.Long itemid)
	{
		setItemID(getContext(), itemid);
	}

	/**
	 * Set value of ItemID
	 * @param context
	 * @param itemid
	 */
	public final void setItemID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long itemid)
	{
		getMendixObject().setValue(context, MemberNames.ItemID.toString(), itemid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ParentLevel
	 */
	public final treeviewdemo.proxies.MultiLevel getParentLevel() throws com.mendix.core.CoreException
	{
		return getParentLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentLevel
	 */
	public final treeviewdemo.proxies.MultiLevel getParentLevel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.MultiLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ParentLevel.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.MultiLevel.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ParentLevel
	 * @param parentlevel
	 */
	public final void setParentLevel(treeviewdemo.proxies.MultiLevel parentlevel)
	{
		setParentLevel(getContext(), parentlevel);
	}

	/**
	 * Set value of ParentLevel
	 * @param context
	 * @param parentlevel
	 */
	public final void setParentLevel(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.MultiLevel parentlevel)
	{
		if (parentlevel == null)
			getMendixObject().setValue(context, MemberNames.ParentLevel.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ParentLevel.toString(), parentlevel.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return multiLevelMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.MultiLevel that = (treeviewdemo.proxies.MultiLevel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.MultiLevel";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
