// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class MultiLevelWidgetData extends treeviewdemo.proxies.TreeViewWidgetData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.MultiLevelWidgetData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NodeSelected("NodeSelected"),
		ExpandToLevel("ExpandToLevel"),
		MaxRecursionLevel("MaxRecursionLevel"),
		Action("Action"),
		NewSelectionKey("NewSelectionKey"),
		NodeChanged("NodeChanged"),
		MultiLevelNodeToDisplay("TreeViewDemo.MultiLevelNodeToDisplay"),
		MultiLevelWidgetData_MultiLevel_New("TreeViewDemo.MultiLevelWidgetData_MultiLevel_New"),
		MultiLevelNodesToUpdate("TreeViewDemo.MultiLevelNodesToUpdate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MultiLevelWidgetData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.MultiLevelWidgetData"));
	}

	protected MultiLevelWidgetData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject multiLevelWidgetDataMendixObject)
	{
		super(context, multiLevelWidgetDataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.MultiLevelWidgetData", multiLevelWidgetDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.MultiLevelWidgetData");
	}

	/**
	 * @deprecated Use 'MultiLevelWidgetData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.MultiLevelWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.MultiLevelWidgetData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.MultiLevelWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeviewdemo.proxies.MultiLevelWidgetData(context, mendixObject);
	}

	public static treeviewdemo.proxies.MultiLevelWidgetData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.MultiLevelWidgetData.initialize(context, mendixObject);
	}

	/**
	 * @return value of NodeSelected
	 */
	public final java.lang.Boolean getNodeSelected()
	{
		return getNodeSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeSelected
	 */
	public final java.lang.Boolean getNodeSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NodeSelected.toString());
	}

	/**
	 * Set value of NodeSelected
	 * @param nodeselected
	 */
	public final void setNodeSelected(java.lang.Boolean nodeselected)
	{
		setNodeSelected(getContext(), nodeselected);
	}

	/**
	 * Set value of NodeSelected
	 * @param context
	 * @param nodeselected
	 */
	public final void setNodeSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean nodeselected)
	{
		getMendixObject().setValue(context, MemberNames.NodeSelected.toString(), nodeselected);
	}

	/**
	 * @return value of ExpandToLevel
	 */
	public final java.lang.Integer getExpandToLevel()
	{
		return getExpandToLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpandToLevel
	 */
	public final java.lang.Integer getExpandToLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExpandToLevel.toString());
	}

	/**
	 * Set value of ExpandToLevel
	 * @param expandtolevel
	 */
	public final void setExpandToLevel(java.lang.Integer expandtolevel)
	{
		setExpandToLevel(getContext(), expandtolevel);
	}

	/**
	 * Set value of ExpandToLevel
	 * @param context
	 * @param expandtolevel
	 */
	public final void setExpandToLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expandtolevel)
	{
		getMendixObject().setValue(context, MemberNames.ExpandToLevel.toString(), expandtolevel);
	}

	/**
	 * @return value of MaxRecursionLevel
	 */
	public final java.lang.Integer getMaxRecursionLevel()
	{
		return getMaxRecursionLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxRecursionLevel
	 */
	public final java.lang.Integer getMaxRecursionLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxRecursionLevel.toString());
	}

	/**
	 * Set value of MaxRecursionLevel
	 * @param maxrecursionlevel
	 */
	public final void setMaxRecursionLevel(java.lang.Integer maxrecursionlevel)
	{
		setMaxRecursionLevel(getContext(), maxrecursionlevel);
	}

	/**
	 * Set value of MaxRecursionLevel
	 * @param context
	 * @param maxrecursionlevel
	 */
	public final void setMaxRecursionLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxrecursionlevel)
	{
		getMendixObject().setValue(context, MemberNames.MaxRecursionLevel.toString(), maxrecursionlevel);
	}

	/**
	 * @return value of MultiLevelNodeToDisplay
	 */
	public final treeviewdemo.proxies.MultiLevelNodeData getMultiLevelNodeToDisplay() throws com.mendix.core.CoreException
	{
		return getMultiLevelNodeToDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiLevelNodeToDisplay
	 */
	public final treeviewdemo.proxies.MultiLevelNodeData getMultiLevelNodeToDisplay(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.MultiLevelNodeData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MultiLevelNodeToDisplay.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.MultiLevelNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MultiLevelNodeToDisplay
	 * @param multilevelnodetodisplay
	 */
	public final void setMultiLevelNodeToDisplay(treeviewdemo.proxies.MultiLevelNodeData multilevelnodetodisplay)
	{
		setMultiLevelNodeToDisplay(getContext(), multilevelnodetodisplay);
	}

	/**
	 * Set value of MultiLevelNodeToDisplay
	 * @param context
	 * @param multilevelnodetodisplay
	 */
	public final void setMultiLevelNodeToDisplay(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.MultiLevelNodeData multilevelnodetodisplay)
	{
		if (multilevelnodetodisplay == null)
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeToDisplay.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeToDisplay.toString(), multilevelnodetodisplay.getMendixObject().getId());
	}

	/**
	 * @return value of MultiLevelWidgetData_MultiLevel_New
	 */
	public final treeviewdemo.proxies.MultiLevel getMultiLevelWidgetData_MultiLevel_New() throws com.mendix.core.CoreException
	{
		return getMultiLevelWidgetData_MultiLevel_New(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiLevelWidgetData_MultiLevel_New
	 */
	public final treeviewdemo.proxies.MultiLevel getMultiLevelWidgetData_MultiLevel_New(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.MultiLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MultiLevelWidgetData_MultiLevel_New.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.MultiLevel.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MultiLevelWidgetData_MultiLevel_New
	 * @param multilevelwidgetdata_multilevel_new
	 */
	public final void setMultiLevelWidgetData_MultiLevel_New(treeviewdemo.proxies.MultiLevel multilevelwidgetdata_multilevel_new)
	{
		setMultiLevelWidgetData_MultiLevel_New(getContext(), multilevelwidgetdata_multilevel_new);
	}

	/**
	 * Set value of MultiLevelWidgetData_MultiLevel_New
	 * @param context
	 * @param multilevelwidgetdata_multilevel_new
	 */
	public final void setMultiLevelWidgetData_MultiLevel_New(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.MultiLevel multilevelwidgetdata_multilevel_new)
	{
		if (multilevelwidgetdata_multilevel_new == null)
			getMendixObject().setValue(context, MemberNames.MultiLevelWidgetData_MultiLevel_New.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MultiLevelWidgetData_MultiLevel_New.toString(), multilevelwidgetdata_multilevel_new.getMendixObject().getId());
	}

	/**
	 * @return value of MultiLevelNodesToUpdate
	 */
	public final java.util.List<treeviewdemo.proxies.MultiLevelNodeData> getMultiLevelNodesToUpdate() throws com.mendix.core.CoreException
	{
		return getMultiLevelNodesToUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiLevelNodesToUpdate
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<treeviewdemo.proxies.MultiLevelNodeData> getMultiLevelNodesToUpdate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<treeviewdemo.proxies.MultiLevelNodeData> result = new java.util.ArrayList<treeviewdemo.proxies.MultiLevelNodeData>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MultiLevelNodesToUpdate.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(treeviewdemo.proxies.MultiLevelNodeData.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MultiLevelNodesToUpdate
	 * @param multilevelnodestoupdate
	 */
	public final void setMultiLevelNodesToUpdate(java.util.List<treeviewdemo.proxies.MultiLevelNodeData> multilevelnodestoupdate)
	{
		setMultiLevelNodesToUpdate(getContext(), multilevelnodestoupdate);
	}

	/**
	 * Set value of MultiLevelNodesToUpdate
	 * @param context
	 * @param multilevelnodestoupdate
	 */
	public final void setMultiLevelNodesToUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<treeviewdemo.proxies.MultiLevelNodeData> multilevelnodestoupdate)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (treeviewdemo.proxies.MultiLevelNodeData proxyObject : multilevelnodestoupdate)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MultiLevelNodesToUpdate.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.MultiLevelWidgetData that = (treeviewdemo.proxies.MultiLevelWidgetData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.MultiLevelWidgetData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
