// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class MultiLevelNodeData extends treeviewdemo.proxies.TreeViewNodeData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.MultiLevelNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		Key("Key"),
		SubnodesLoaded("SubnodesLoaded"),
		HasChildren("HasChildren"),
		MultiLevelNodeData_MultiLevelWidgetData("TreeViewDemo.MultiLevelNodeData_MultiLevelWidgetData"),
		MultiLevelNodeData_MultiLevel("TreeViewDemo.MultiLevelNodeData_MultiLevel"),
		ParentNode("TreeViewDemo.ParentNode"),
		TreeViewNodeData_TreeViewWidgetData("TreeViewDemo.TreeViewNodeData_TreeViewWidgetData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MultiLevelNodeData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.MultiLevelNodeData"));
	}

	protected MultiLevelNodeData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject multiLevelNodeDataMendixObject)
	{
		super(context, multiLevelNodeDataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.MultiLevelNodeData", multiLevelNodeDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.MultiLevelNodeData");
	}

	/**
	 * @deprecated Use 'MultiLevelNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.MultiLevelNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.MultiLevelNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.MultiLevelNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeviewdemo.proxies.MultiLevelNodeData(context, mendixObject);
	}

	public static treeviewdemo.proxies.MultiLevelNodeData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.MultiLevelNodeData.initialize(context, mendixObject);
	}

	/**
	 * @return value of MultiLevelNodeData_MultiLevelWidgetData
	 */
	public final treeviewdemo.proxies.MultiLevelWidgetData getMultiLevelNodeData_MultiLevelWidgetData() throws com.mendix.core.CoreException
	{
		return getMultiLevelNodeData_MultiLevelWidgetData(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiLevelNodeData_MultiLevelWidgetData
	 */
	public final treeviewdemo.proxies.MultiLevelWidgetData getMultiLevelNodeData_MultiLevelWidgetData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.MultiLevelWidgetData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MultiLevelNodeData_MultiLevelWidgetData.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.MultiLevelWidgetData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MultiLevelNodeData_MultiLevelWidgetData
	 * @param multilevelnodedata_multilevelwidgetdata
	 */
	public final void setMultiLevelNodeData_MultiLevelWidgetData(treeviewdemo.proxies.MultiLevelWidgetData multilevelnodedata_multilevelwidgetdata)
	{
		setMultiLevelNodeData_MultiLevelWidgetData(getContext(), multilevelnodedata_multilevelwidgetdata);
	}

	/**
	 * Set value of MultiLevelNodeData_MultiLevelWidgetData
	 * @param context
	 * @param multilevelnodedata_multilevelwidgetdata
	 */
	public final void setMultiLevelNodeData_MultiLevelWidgetData(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.MultiLevelWidgetData multilevelnodedata_multilevelwidgetdata)
	{
		if (multilevelnodedata_multilevelwidgetdata == null)
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeData_MultiLevelWidgetData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeData_MultiLevelWidgetData.toString(), multilevelnodedata_multilevelwidgetdata.getMendixObject().getId());
	}

	/**
	 * @return value of MultiLevelNodeData_MultiLevel
	 */
	public final treeviewdemo.proxies.MultiLevel getMultiLevelNodeData_MultiLevel() throws com.mendix.core.CoreException
	{
		return getMultiLevelNodeData_MultiLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiLevelNodeData_MultiLevel
	 */
	public final treeviewdemo.proxies.MultiLevel getMultiLevelNodeData_MultiLevel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.MultiLevel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MultiLevelNodeData_MultiLevel.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.MultiLevel.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MultiLevelNodeData_MultiLevel
	 * @param multilevelnodedata_multilevel
	 */
	public final void setMultiLevelNodeData_MultiLevel(treeviewdemo.proxies.MultiLevel multilevelnodedata_multilevel)
	{
		setMultiLevelNodeData_MultiLevel(getContext(), multilevelnodedata_multilevel);
	}

	/**
	 * Set value of MultiLevelNodeData_MultiLevel
	 * @param context
	 * @param multilevelnodedata_multilevel
	 */
	public final void setMultiLevelNodeData_MultiLevel(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.MultiLevel multilevelnodedata_multilevel)
	{
		if (multilevelnodedata_multilevel == null)
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeData_MultiLevel.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MultiLevelNodeData_MultiLevel.toString(), multilevelnodedata_multilevel.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.MultiLevelNodeData that = (treeviewdemo.proxies.MultiLevelNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.MultiLevelNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
