// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class ProductTreeWidgetData extends treeviewdemo.proxies.TreeViewWidgetData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.ProductTreeWidgetData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectionType("SelectionType"),
		Action("Action"),
		NewSelectionKey("NewSelectionKey"),
		NodeChanged("NodeChanged"),
		ProductTreeNodeToDisplay("TreeViewDemo.ProductTreeNodeToDisplay"),
		ProductTreeWidgetData_Product_New("TreeViewDemo.ProductTreeWidgetData_Product_New"),
		ProductTreeWidgetData_DraggedNode("TreeViewDemo.ProductTreeWidgetData_DraggedNode"),
		ProductTreeWidgetData_DropTargetNode("TreeViewDemo.ProductTreeWidgetData_DropTargetNode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductTreeWidgetData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.ProductTreeWidgetData"));
	}

	protected ProductTreeWidgetData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productTreeWidgetDataMendixObject)
	{
		super(context, productTreeWidgetDataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.ProductTreeWidgetData", productTreeWidgetDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.ProductTreeWidgetData");
	}

	/**
	 * @deprecated Use 'ProductTreeWidgetData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static treeviewdemo.proxies.ProductTreeWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.ProductTreeWidgetData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.ProductTreeWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeviewdemo.proxies.ProductTreeWidgetData(context, mendixObject);
	}

	public static treeviewdemo.proxies.ProductTreeWidgetData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.ProductTreeWidgetData.initialize(context, mendixObject);
	}

	/**
	 * Set value of SelectionType
	 * @param selectiontype
	 */
	public final treeviewdemo.proxies.ProductTreeSelectionType getSelectionType()
	{
		return getSelectionType(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectionType
	 */
	public final treeviewdemo.proxies.ProductTreeSelectionType getSelectionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SelectionType.toString());
		if (obj == null)
			return null;

		return treeviewdemo.proxies.ProductTreeSelectionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SelectionType
	 * @param selectiontype
	 */
	public final void setSelectionType(treeviewdemo.proxies.ProductTreeSelectionType selectiontype)
	{
		setSelectionType(getContext(), selectiontype);
	}

	/**
	 * Set value of SelectionType
	 * @param context
	 * @param selectiontype
	 */
	public final void setSelectionType(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.ProductTreeSelectionType selectiontype)
	{
		if (selectiontype != null)
			getMendixObject().setValue(context, MemberNames.SelectionType.toString(), selectiontype.toString());
		else
			getMendixObject().setValue(context, MemberNames.SelectionType.toString(), null);
	}

	/**
	 * @return value of ProductTreeNodeToDisplay
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeNodeToDisplay() throws com.mendix.core.CoreException
	{
		return getProductTreeNodeToDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductTreeNodeToDisplay
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeNodeToDisplay(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.ProductTreeNodeData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductTreeNodeToDisplay.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.ProductTreeNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductTreeNodeToDisplay
	 * @param producttreenodetodisplay
	 */
	public final void setProductTreeNodeToDisplay(treeviewdemo.proxies.ProductTreeNodeData producttreenodetodisplay)
	{
		setProductTreeNodeToDisplay(getContext(), producttreenodetodisplay);
	}

	/**
	 * Set value of ProductTreeNodeToDisplay
	 * @param context
	 * @param producttreenodetodisplay
	 */
	public final void setProductTreeNodeToDisplay(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.ProductTreeNodeData producttreenodetodisplay)
	{
		if (producttreenodetodisplay == null)
			getMendixObject().setValue(context, MemberNames.ProductTreeNodeToDisplay.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductTreeNodeToDisplay.toString(), producttreenodetodisplay.getMendixObject().getId());
	}

	/**
	 * @return value of ProductTreeWidgetData_Product_New
	 */
	public final treeviewdemo.proxies.Product getProductTreeWidgetData_Product_New() throws com.mendix.core.CoreException
	{
		return getProductTreeWidgetData_Product_New(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductTreeWidgetData_Product_New
	 */
	public final treeviewdemo.proxies.Product getProductTreeWidgetData_Product_New(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductTreeWidgetData_Product_New.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductTreeWidgetData_Product_New
	 * @param producttreewidgetdata_product_new
	 */
	public final void setProductTreeWidgetData_Product_New(treeviewdemo.proxies.Product producttreewidgetdata_product_new)
	{
		setProductTreeWidgetData_Product_New(getContext(), producttreewidgetdata_product_new);
	}

	/**
	 * Set value of ProductTreeWidgetData_Product_New
	 * @param context
	 * @param producttreewidgetdata_product_new
	 */
	public final void setProductTreeWidgetData_Product_New(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.Product producttreewidgetdata_product_new)
	{
		if (producttreewidgetdata_product_new == null)
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_Product_New.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_Product_New.toString(), producttreewidgetdata_product_new.getMendixObject().getId());
	}

	/**
	 * @return value of ProductTreeWidgetData_DraggedNode
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeWidgetData_DraggedNode() throws com.mendix.core.CoreException
	{
		return getProductTreeWidgetData_DraggedNode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductTreeWidgetData_DraggedNode
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeWidgetData_DraggedNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.ProductTreeNodeData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductTreeWidgetData_DraggedNode.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.ProductTreeNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductTreeWidgetData_DraggedNode
	 * @param producttreewidgetdata_draggednode
	 */
	public final void setProductTreeWidgetData_DraggedNode(treeviewdemo.proxies.ProductTreeNodeData producttreewidgetdata_draggednode)
	{
		setProductTreeWidgetData_DraggedNode(getContext(), producttreewidgetdata_draggednode);
	}

	/**
	 * Set value of ProductTreeWidgetData_DraggedNode
	 * @param context
	 * @param producttreewidgetdata_draggednode
	 */
	public final void setProductTreeWidgetData_DraggedNode(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.ProductTreeNodeData producttreewidgetdata_draggednode)
	{
		if (producttreewidgetdata_draggednode == null)
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_DraggedNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_DraggedNode.toString(), producttreewidgetdata_draggednode.getMendixObject().getId());
	}

	/**
	 * @return value of ProductTreeWidgetData_DropTargetNode
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeWidgetData_DropTargetNode() throws com.mendix.core.CoreException
	{
		return getProductTreeWidgetData_DropTargetNode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductTreeWidgetData_DropTargetNode
	 */
	public final treeviewdemo.proxies.ProductTreeNodeData getProductTreeWidgetData_DropTargetNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.ProductTreeNodeData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductTreeWidgetData_DropTargetNode.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.ProductTreeNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductTreeWidgetData_DropTargetNode
	 * @param producttreewidgetdata_droptargetnode
	 */
	public final void setProductTreeWidgetData_DropTargetNode(treeviewdemo.proxies.ProductTreeNodeData producttreewidgetdata_droptargetnode)
	{
		setProductTreeWidgetData_DropTargetNode(getContext(), producttreewidgetdata_droptargetnode);
	}

	/**
	 * Set value of ProductTreeWidgetData_DropTargetNode
	 * @param context
	 * @param producttreewidgetdata_droptargetnode
	 */
	public final void setProductTreeWidgetData_DropTargetNode(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.ProductTreeNodeData producttreewidgetdata_droptargetnode)
	{
		if (producttreewidgetdata_droptargetnode == null)
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_DropTargetNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductTreeWidgetData_DropTargetNode.toString(), producttreewidgetdata_droptargetnode.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.ProductTreeWidgetData that = (treeviewdemo.proxies.ProductTreeWidgetData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.ProductTreeWidgetData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
