// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class ProductGroupNodeData extends treeviewdemo.proxies.ProductTreeNodeData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.ProductGroupNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		DraggableClass("DraggableClass"),
		DropTargetSelector("DropTargetSelector"),
		Key("Key"),
		SubnodesLoaded("SubnodesLoaded"),
		HasChildren("HasChildren"),
		ProductGroupNodeData_ProductGroup("TreeViewDemo.ProductGroupNodeData_ProductGroup"),
		ProductTreeNodeData_ProductTreeWidgetData("TreeViewDemo.ProductTreeNodeData_ProductTreeWidgetData"),
		ParentNode("TreeViewDemo.ParentNode"),
		TreeViewNodeData_TreeViewWidgetData("TreeViewDemo.TreeViewNodeData_TreeViewWidgetData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductGroupNodeData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.ProductGroupNodeData"));
	}

	protected ProductGroupNodeData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productGroupNodeDataMendixObject)
	{
		super(context, productGroupNodeDataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.ProductGroupNodeData", productGroupNodeDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.ProductGroupNodeData");
	}

	/**
	 * @deprecated Use 'ProductGroupNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.ProductGroupNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.ProductGroupNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.ProductGroupNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeviewdemo.proxies.ProductGroupNodeData(context, mendixObject);
	}

	public static treeviewdemo.proxies.ProductGroupNodeData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.ProductGroupNodeData.initialize(context, mendixObject);
	}

	/**
	 * @return value of ProductGroupNodeData_ProductGroup
	 */
	public final treeviewdemo.proxies.ProductGroup getProductGroupNodeData_ProductGroup() throws com.mendix.core.CoreException
	{
		return getProductGroupNodeData_ProductGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductGroupNodeData_ProductGroup
	 */
	public final treeviewdemo.proxies.ProductGroup getProductGroupNodeData_ProductGroup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.ProductGroup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.ProductGroup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductGroupNodeData_ProductGroup
	 * @param productgroupnodedata_productgroup
	 */
	public final void setProductGroupNodeData_ProductGroup(treeviewdemo.proxies.ProductGroup productgroupnodedata_productgroup)
	{
		setProductGroupNodeData_ProductGroup(getContext(), productgroupnodedata_productgroup);
	}

	/**
	 * Set value of ProductGroupNodeData_ProductGroup
	 * @param context
	 * @param productgroupnodedata_productgroup
	 */
	public final void setProductGroupNodeData_ProductGroup(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.ProductGroup productgroupnodedata_productgroup)
	{
		if (productgroupnodedata_productgroup == null)
			getMendixObject().setValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductGroupNodeData_ProductGroup.toString(), productgroupnodedata_productgroup.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.ProductGroupNodeData that = (treeviewdemo.proxies.ProductGroupNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.ProductGroupNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
