// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class TreeViewNodeData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject treeViewNodeDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.TreeViewNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		DraggableClass("DraggableClass"),
		DropTargetSelector("DropTargetSelector"),
		Key("Key"),
		SubnodesLoaded("SubnodesLoaded"),
		HasChildren("HasChildren"),
		ParentNode("TreeViewDemo.ParentNode"),
		TreeViewNodeData_TreeViewWidgetData("TreeViewDemo.TreeViewNodeData_TreeViewWidgetData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TreeViewNodeData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.TreeViewNodeData"));
	}

	protected TreeViewNodeData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject treeViewNodeDataMendixObject)
	{
		if (treeViewNodeDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.TreeViewNodeData", treeViewNodeDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.TreeViewNodeData");

		this.treeViewNodeDataMendixObject = treeViewNodeDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TreeViewNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.TreeViewNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.TreeViewNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.TreeViewNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("TreeViewDemo.MultiLevelNodeData", mendixObject.getType()))
			return treeviewdemo.proxies.MultiLevelNodeData.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("TreeViewDemo.ProductTreeNodeData", mendixObject.getType()))
			return treeviewdemo.proxies.ProductTreeNodeData.initialize(context, mendixObject);

		return new treeviewdemo.proxies.TreeViewNodeData(context, mendixObject);
	}

	public static treeviewdemo.proxies.TreeViewNodeData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.TreeViewNodeData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Caption
	 */
	public final java.lang.String getCaption()
	{
		return getCaption(getContext());
	}

	/**
	 * @param context
	 * @return value of Caption
	 */
	public final java.lang.String getCaption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Caption.toString());
	}

	/**
	 * Set value of Caption
	 * @param caption
	 */
	public final void setCaption(java.lang.String caption)
	{
		setCaption(getContext(), caption);
	}

	/**
	 * Set value of Caption
	 * @param context
	 * @param caption
	 */
	public final void setCaption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String caption)
	{
		getMendixObject().setValue(context, MemberNames.Caption.toString(), caption);
	}

	/**
	 * @return value of NodeClass
	 */
	public final java.lang.String getNodeClass()
	{
		return getNodeClass(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeClass
	 */
	public final java.lang.String getNodeClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeClass.toString());
	}

	/**
	 * Set value of NodeClass
	 * @param nodeclass
	 */
	public final void setNodeClass(java.lang.String nodeclass)
	{
		setNodeClass(getContext(), nodeclass);
	}

	/**
	 * Set value of NodeClass
	 * @param context
	 * @param nodeclass
	 */
	public final void setNodeClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeclass)
	{
		getMendixObject().setValue(context, MemberNames.NodeClass.toString(), nodeclass);
	}

	/**
	 * @return value of DraggableClass
	 */
	public final java.lang.String getDraggableClass()
	{
		return getDraggableClass(getContext());
	}

	/**
	 * @param context
	 * @return value of DraggableClass
	 */
	public final java.lang.String getDraggableClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DraggableClass.toString());
	}

	/**
	 * Set value of DraggableClass
	 * @param draggableclass
	 */
	public final void setDraggableClass(java.lang.String draggableclass)
	{
		setDraggableClass(getContext(), draggableclass);
	}

	/**
	 * Set value of DraggableClass
	 * @param context
	 * @param draggableclass
	 */
	public final void setDraggableClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String draggableclass)
	{
		getMendixObject().setValue(context, MemberNames.DraggableClass.toString(), draggableclass);
	}

	/**
	 * @return value of DropTargetSelector
	 */
	public final java.lang.String getDropTargetSelector()
	{
		return getDropTargetSelector(getContext());
	}

	/**
	 * @param context
	 * @return value of DropTargetSelector
	 */
	public final java.lang.String getDropTargetSelector(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DropTargetSelector.toString());
	}

	/**
	 * Set value of DropTargetSelector
	 * @param droptargetselector
	 */
	public final void setDropTargetSelector(java.lang.String droptargetselector)
	{
		setDropTargetSelector(getContext(), droptargetselector);
	}

	/**
	 * Set value of DropTargetSelector
	 * @param context
	 * @param droptargetselector
	 */
	public final void setDropTargetSelector(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String droptargetselector)
	{
		getMendixObject().setValue(context, MemberNames.DropTargetSelector.toString(), droptargetselector);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of SubnodesLoaded
	 */
	public final java.lang.Boolean getSubnodesLoaded()
	{
		return getSubnodesLoaded(getContext());
	}

	/**
	 * @param context
	 * @return value of SubnodesLoaded
	 */
	public final java.lang.Boolean getSubnodesLoaded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SubnodesLoaded.toString());
	}

	/**
	 * Set value of SubnodesLoaded
	 * @param subnodesloaded
	 */
	public final void setSubnodesLoaded(java.lang.Boolean subnodesloaded)
	{
		setSubnodesLoaded(getContext(), subnodesloaded);
	}

	/**
	 * Set value of SubnodesLoaded
	 * @param context
	 * @param subnodesloaded
	 */
	public final void setSubnodesLoaded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean subnodesloaded)
	{
		getMendixObject().setValue(context, MemberNames.SubnodesLoaded.toString(), subnodesloaded);
	}

	/**
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren()
	{
		return getHasChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasChildren.toString());
	}

	/**
	 * Set value of HasChildren
	 * @param haschildren
	 */
	public final void setHasChildren(java.lang.Boolean haschildren)
	{
		setHasChildren(getContext(), haschildren);
	}

	/**
	 * Set value of HasChildren
	 * @param context
	 * @param haschildren
	 */
	public final void setHasChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haschildren)
	{
		getMendixObject().setValue(context, MemberNames.HasChildren.toString(), haschildren);
	}

	/**
	 * @return value of ParentNode
	 */
	public final treeviewdemo.proxies.TreeViewNodeData getParentNode() throws com.mendix.core.CoreException
	{
		return getParentNode(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentNode
	 */
	public final treeviewdemo.proxies.TreeViewNodeData getParentNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.TreeViewNodeData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ParentNode.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.TreeViewNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ParentNode
	 * @param parentnode
	 */
	public final void setParentNode(treeviewdemo.proxies.TreeViewNodeData parentnode)
	{
		setParentNode(getContext(), parentnode);
	}

	/**
	 * Set value of ParentNode
	 * @param context
	 * @param parentnode
	 */
	public final void setParentNode(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.TreeViewNodeData parentnode)
	{
		if (parentnode == null)
			getMendixObject().setValue(context, MemberNames.ParentNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ParentNode.toString(), parentnode.getMendixObject().getId());
	}

	/**
	 * @return value of TreeViewNodeData_TreeViewWidgetData
	 */
	public final treeviewdemo.proxies.TreeViewWidgetData getTreeViewNodeData_TreeViewWidgetData() throws com.mendix.core.CoreException
	{
		return getTreeViewNodeData_TreeViewWidgetData(getContext());
	}

	/**
	 * @param context
	 * @return value of TreeViewNodeData_TreeViewWidgetData
	 */
	public final treeviewdemo.proxies.TreeViewWidgetData getTreeViewNodeData_TreeViewWidgetData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeviewdemo.proxies.TreeViewWidgetData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TreeViewNodeData_TreeViewWidgetData.toString());
		if (identifier != null)
			result = treeviewdemo.proxies.TreeViewWidgetData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TreeViewNodeData_TreeViewWidgetData
	 * @param treeviewnodedata_treeviewwidgetdata
	 */
	public final void setTreeViewNodeData_TreeViewWidgetData(treeviewdemo.proxies.TreeViewWidgetData treeviewnodedata_treeviewwidgetdata)
	{
		setTreeViewNodeData_TreeViewWidgetData(getContext(), treeviewnodedata_treeviewwidgetdata);
	}

	/**
	 * Set value of TreeViewNodeData_TreeViewWidgetData
	 * @param context
	 * @param treeviewnodedata_treeviewwidgetdata
	 */
	public final void setTreeViewNodeData_TreeViewWidgetData(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.TreeViewWidgetData treeviewnodedata_treeviewwidgetdata)
	{
		if (treeviewnodedata_treeviewwidgetdata == null)
			getMendixObject().setValue(context, MemberNames.TreeViewNodeData_TreeViewWidgetData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TreeViewNodeData_TreeViewWidgetData.toString(), treeviewnodedata_treeviewwidgetdata.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return treeViewNodeDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.TreeViewNodeData that = (treeviewdemo.proxies.TreeViewNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.TreeViewNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
