// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies;

public class TreeViewWidgetData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject treeViewWidgetDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeViewDemo.TreeViewWidgetData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Action("Action"),
		NewSelectionKey("NewSelectionKey");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TreeViewWidgetData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeViewDemo.TreeViewWidgetData"));
	}

	protected TreeViewWidgetData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject treeViewWidgetDataMendixObject)
	{
		if (treeViewWidgetDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TreeViewDemo.TreeViewWidgetData", treeViewWidgetDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeViewDemo.TreeViewWidgetData");

		this.treeViewWidgetDataMendixObject = treeViewWidgetDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TreeViewWidgetData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static treeviewdemo.proxies.TreeViewWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treeviewdemo.proxies.TreeViewWidgetData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static treeviewdemo.proxies.TreeViewWidgetData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("TreeViewDemo.ProductTreeWidgetData", mendixObject.getType()))
			return treeviewdemo.proxies.ProductTreeWidgetData.initialize(context, mendixObject);

		return new treeviewdemo.proxies.TreeViewWidgetData(context, mendixObject);
	}

	public static treeviewdemo.proxies.TreeViewWidgetData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeviewdemo.proxies.TreeViewWidgetData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Action
	 * @param action
	 */
	public final treeviewdemo.proxies.TreeViewAction getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final treeviewdemo.proxies.TreeViewAction getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Action.toString());
		if (obj == null)
			return null;

		return treeviewdemo.proxies.TreeViewAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(treeviewdemo.proxies.TreeViewAction action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, treeviewdemo.proxies.TreeViewAction action)
	{
		if (action != null)
			getMendixObject().setValue(context, MemberNames.Action.toString(), action.toString());
		else
			getMendixObject().setValue(context, MemberNames.Action.toString(), null);
	}

	/**
	 * @return value of NewSelectionKey
	 */
	public final java.lang.String getNewSelectionKey()
	{
		return getNewSelectionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of NewSelectionKey
	 */
	public final java.lang.String getNewSelectionKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NewSelectionKey.toString());
	}

	/**
	 * Set value of NewSelectionKey
	 * @param newselectionkey
	 */
	public final void setNewSelectionKey(java.lang.String newselectionkey)
	{
		setNewSelectionKey(getContext(), newselectionkey);
	}

	/**
	 * Set value of NewSelectionKey
	 * @param context
	 * @param newselectionkey
	 */
	public final void setNewSelectionKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String newselectionkey)
	{
		getMendixObject().setValue(context, MemberNames.NewSelectionKey.toString(), newselectionkey);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return treeViewWidgetDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeviewdemo.proxies.TreeViewWidgetData that = (treeviewdemo.proxies.TreeViewWidgetData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeViewDemo.TreeViewWidgetData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
