// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

/**
 * 
 */
public class ProductNodeData extends myfirstmodule.proxies.ProductTreeNodeData
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ProductNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		Key("Key"),
		ProductNodeData_Product("MyFirstModule.ProductNodeData_Product"),
		ProductTreeNodeData_ProductTreeWidgetData("MyFirstModule.ProductTreeNodeData_ProductTreeWidgetData"),
		ParentNode("MyFirstModule.ParentNode"),
		TreeViewNodeData_TreeViewWidgetData("MyFirstModule.TreeViewNodeData_TreeViewWidgetData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductNodeData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.ProductNodeData"));
	}

	protected ProductNodeData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productNodeDataMendixObject)
	{
		super(context, productNodeDataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.ProductNodeData", productNodeDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.ProductNodeData");
	}

	/**
	 * @deprecated Use 'ProductNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.ProductNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ProductNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ProductNodeData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ProductNodeData(context, mendixObject);
	}

	public static myfirstmodule.proxies.ProductNodeData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ProductNodeData.initialize(context, mendixObject);
	}

	/**
	 * @return value of ProductNodeData_Product
	 */
	public final myfirstmodule.proxies.Product getProductNodeData_Product() throws com.mendix.core.CoreException
	{
		return getProductNodeData_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductNodeData_Product
	 */
	public final myfirstmodule.proxies.Product getProductNodeData_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProductNodeData_Product.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProductNodeData_Product
	 * @param productnodedata_product
	 */
	public final void setProductNodeData_Product(myfirstmodule.proxies.Product productnodedata_product)
	{
		setProductNodeData_Product(getContext(), productnodedata_product);
	}

	/**
	 * Set value of ProductNodeData_Product
	 * @param context
	 * @param productnodedata_product
	 */
	public final void setProductNodeData_Product(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Product productnodedata_product)
	{
		if (productnodedata_product == null)
			getMendixObject().setValue(context, MemberNames.ProductNodeData_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProductNodeData_Product.toString(), productnodedata_product.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ProductNodeData that = (myfirstmodule.proxies.ProductNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.ProductNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
