// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeviewdemo.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TreeViewDemo module

	public static java.lang.String getLOGNODE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TreeViewDemo.LOGNODE");
	}
}